export const fakeBarberApi = [
  {
    id: "1",
    image: "/images/barbershop-api/guts.jpg",
    title: "Guts Barbershop",
    ratings: "3.5",
    location: "NIBM, Kondhwa - 411048",
    tags: "Barbershop",
    locationLink: "/",
  },
  {
    id: "2",
    image: "/images/barbershop-api/barberinn.jpeg",
    title: "BarberInn",
    ratings: "3",
    location: "Kausarbaug, Kondhwa - 411048",
    tags: "Barbershop",
    locationLink: "/",
  },
  {
    id: "3",
    image: "/images/barbershop-api/green.jpg",
    title: "Green",
    ratings: "2.5",
    location: "NIBM, Kondhwa Khurd - 411048",
    tags: "Salon",
    locationLink: "/",
  },
  {
    id: "4",
    image: "/images/barbershop-api/geetanjali.jpg",
    title: "Geetanjali",
    ratings: "4",
    location: "Koregaon Park",
    tags: "Salon",
    locationLink: "/",
  },
  {
    id: "5",
    image: "/images/barbershop-api/littlehair.jpg",
    title: "Little Hair",
    ratings: "4.5",
    location: "Koregaon Park",
    tags: "Barbershop",
    locationLink: "/",
  },
];
